### ISSUE TITLE
Why  download  the csv file , is a version https://git-lfs.github.com/spec/v1 oid sha256:3207c5d96b1b404b3d371bf4692369c90602f532b4861664567836eaef089465 size 230, not  a file?

### ISSUE THREAD

**Issue by starzhouchina** [dipanjanS/practical-machine-learning-with-python#1]
Why  download  the csv file , is a version https://git-lfs.github.com/spec/v1 oid sha256:3207c5d96b1b404b3d371bf4692369c90602f532b4861664567836eaef089465 size 230, not  a file?

**Comment by dipanjanS** [comment]
Can you please be more specific about which file you were trying to donwload and what issue did you face? The message you have posted is not giving enough information for us to check this out.

**Comment by dipanjanS** [comment]
This was likely because Git LFS limits exceeded for this repository due to many people using it. I have purchased a new plan for the same. It should work now.

**Comment by starzhouchina** [comment]
Very good！
OK，Thank you！

**Comment by xx2416** [comment]
could u plz show me how to fix this problem ?
