### ISSUE TITLE
Showing error while importing arima-Utils ,lstm_utils

### ISSUE THREAD

**Issue by ankurmedhi** [dipanjanS/practical-machine-learning-with-python#16]
Below Error are appearing :

from arima_utils import ad_fuller_test, plot_rolling_stats
from arima_utils import plot_acf_pacf, arima_gridsearch_cv

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-4087ebd1fdfd> in <module>
----> 1 from arima_utils import ad_fuller_test, plot_rolling_stats
      2 from arima_utils import plot_acf_pacf, arima_gridsearch_cv

ModuleNotFoundError: No module named 'arima_utils'

while trying import getting below error :   
PS C:\Users\ankur> pip install arima_utils
Collecting arima_utils
  Could not find a version that satisfies the requirement arima_utils (from versions: )
No matching distribution found for arima_utils

Is there any user-defined utils? if yes, please send me the link .

**Comment by dipanjanS** [comment]
You need to read through the chapter of the book to know the steps to run the notebook. An alternate approach would be to download the full code of Chapter 11 from here: https://github.com/dipanjanS/practical-machine-learning-with-python/tree/master/notebooks/Ch11_Forecasting_Stock_and_Commodity_Prices and make sure all the files are present along with the notebooks.

The `arima_utils` and `lstm_utils` are both created by us and hence not a part of any standard library and you will find them in that folder itself mentioned in the preceding link.

**Comment by ankurmedhi** [comment]
thank you..got it..

**Comment by JanosVrbata** [comment]
ahaaaaaaa, sorry for that.
