### ISSUE TITLE
Chapter 4 feature engineering numeric data notebook broken on GitHub

### ISSUE THREAD

**Issue by ArturKlauser** [dipanjanS/practical-machine-learning-with-python#39]
As of 2023-12-26, the notebook
notebooks/Ch04_Feature_Engineering_and_Selection/Feature Engineering on Numeric Data.ipynb
doesn’t render on the GitHub site, but instead results in an error page.

**Comment by raghavbali** [comment]
Try clearing browser cache or trying a different rendering application @ArturKlauser (see below screenshot, seems to be working for me)
<img width="1101" alt="image" src="https://github.com/dipanjanS/practical-machine-learning-with-python/assets/3089481/f8f460c4-6f8f-491d-b7fa-21aeb2cbb345">
