### ISSUE TITLE
Puzzle for Ch7, clean data, normalize_corpus(test_reviews)

### ISSUE THREAD

**Issue by xiaoguo1995** [dipanjanS/practical-machine-learning-with-python#4]
Since we have already implemented "normalize_corpus" function, why there is still **<br /><br />** after cleaning? 

I simply pick 35002th comment... so confusing.
```
test_reviews = reviews[35000:35005]

sample_review_ids = [1, 2, 3]
```

REVIEW: Be careful with this one. Once you get yer mitts on it, it'll change the way you look at kung-fu flicks. You will be yearning a plot from all of the kung-fu films now, you will be wanting character depth and development, you will be craving mystery and unpredictability, you will demand dynamic camera work and incredible backdrops. Sadly, you won't find all of these aspects together in one kung-fu movie, EXCEPT for Five Deadl**y Venoms!<br /><br />Eas**ily the best kung-fu movie of all-time, Venoms blends a rich plot, full of twists and turns, with colourful (and developed) characters, along with some of the best camerawork to come out of the 70s. The success of someone liking the film depends on the viewers ability to decipher which character is which, and who specializes in what venom. One is the Centipede, two is the Snake, three is the Scorpion, four is the Lizard, and five is the Toad. Each character has different traits, characteristics, strengths, and weaknesses. Therein lies the hook, we learn along with the student character, finding out who these different men turn out to be. We are in his shoes (so to speak), and we have to pick who we trust, and who we don't, just like he does. We learn along with **him.<br /><br />N**ot only is the plot, the characters, and the camerawork great, it's also fun to watch, which in my book makes it more valuable than almost any other movie of it's kind. It's worth quite a few watches to pick up on everything that's going on. Venoms is a lesson on what kung-fu can really do...just don't expect many other kung-fu films to live up to it's gauntlet.
Actual Sentiment: positive
Predicted Sentiment polarity: 28.0

**Comment by raghavbali** [comment]
@dipanjanS could you check this once please. Thanks :)

**Comment by dipanjanS** [comment]
@PeterXiaoGuo Your question is not clear, which notebook or what part of the code is not working for you? 

If you are talking about the unsupervised lexicon sentiment, we are not using all the pre-processing\text normalization because most of these frameworks handle them directly and we do some very basic pre-processing for VADER sentiment (no need of lemmatization etc.)

**Comment by dipanjanS** [comment]
Closing this due to lack of further activity (> 1 month). Feel free to reach out in the future as needed or open a new issue in case of further problems.
