### ISSUE TITLE
Minor import issue with notebook_gold_forecast_arima.ipynb

### ISSUE THREAD

**Issue by abhishektzr** [dipanjanS/practical-machine-learning-with-python#8]
In the file "notebook_gold_forecast_arima" the following needs to be updated to import correctly...

from time_series_utils import ad_fuller_test, plot_rolling_stats
from time_series_utils import plot_acf_pacf, arima_gridsearch_cv

TO

from arima_utils import ad_fuller_test, plot_rolling_stats
from arima_utils import plot_acf_pacf, arima_gridsearch_cv

**Comment by raghavbali** [comment]
Thanks for checking @abhibee (keen eye 😉), will update this in next push.

**Comment by liyanonline** [comment]
Fine. Thanks!

**Comment by Donsuno** [comment]
These code is still not worked on me, I don't get it. Can u help me?

**Comment by raghavbali** [comment]
@Donsuno could you be more specific? please share the error and code snippet which is erring out along with your environment details (python version, OS , etc)

**Comment by raghavbali** [comment]
Closing this issue due to no further discussion/details.
